### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by nunsie** [nunsie/truffle-hdwallet-provider-xprv#1]
Documentation needs to reflect the correct usage for this module as well as the correct intended purpose.

**Comment by mct-dev** [comment]
Got any more info here, @nunsie?  Is the documentation in the code base somewhere?  What change would reflect the correct usage?  Are there any specific examples of the documentation reflecting incorrect usage?

**Comment by nunsie** [comment]
@mct-dev - just updated the docs myself in #5 , didn't think anyone was gonna pick this up

**Comment by mct-dev** [comment]
Ahh gotcha. No worries.

**Comment by nunsie** [comment]
@mct-dev The truffle usage needs to be updated to reflect "truffle-hdwallet-provider-xprv" instead of "truffle-hdwallet-provider" if you're keen on making that tiny change - quick hacktoberfest pr win ;)

**Comment by mct-dev** [comment]
@nunsie -- ON IT.  DON'T WORRY, I GOT THIS ONE.
